#' Add functional information of taxa to a heatmap
#'
#' Generates a table with functional information about the taxa in an input heatmap and combines the two. 
#'
#' @usage amp_function(heatmap)
#'
#' @param heatmap (required) A heatmap as generated by \code{\link{amp_heatmap}}.
#' @param function_data A data frame with functional information about genus-level OTUs. If none provided, the \code{data("MiF")} dataset will be used.
#' @param adjust_bottom Adjust the whitespace at the bottom of the plot in mm. (\emph{default:} \code{10})
#' @param adjust_top Adjust the whitespace at the top of the plot in mm. (\emph{default:} \code{0})
#' @param genus_pos Specify which part of the name that contains the genus name. Fx if the taxa names are in the form "Phylum; Genus", set this to \code{2}. (\emph{default:} \code{1})
#' @param point_size Size of the plotted points. (\emph{default:} \code{6})
#' @param plotted_functions A vector with the functions to be displayed. (\emph{default:} \code{c("MiDAS","FIL", "AOB", "NOB", "PAO", "GAO")})
#' 
#' @return A ggplot2 object.
#' @import ggplot2
#' @import gridExtra
#' 
#' @export
#' 
#' @details The current state of this function requires the provided heatmap to be either aggregated to Genus (with \code{tax_aggregate}, note the default is \code{"Phylum"}) or the Genus names be added with \code{tax_add}. 
#' 
#' @examples 
#' #Load example data
#' data("AalborgWWTPs")
#' 
#' #Save a heatmap, aggregating to Genus level is a must
#' heatmap <- amp_heatmap(AalborgWWTPs, group_by = "Plant", tax_aggregate = "Genus")
#' 
#' #Generate the function table based on the input heatmap and show the two side by side
#' amp_function(heatmap)
#' 
#' @author Kasper Skytte Andersen \email{kasperskytteandersen@@gmail.com}
#' @author Mads Albertsen \email{MadsAlbertsen85@@gmail.com}

amp_function <- function(heatmap, 
                         function_data = NULL, 
                         adjust_bottom = 10, 
                         adjust_top = 0, 
                         genus_pos = 1, 
                         point_size = 6, 
                         plotted_functions=c("MiDAS","FIL", "AOB", "NOB", "PAO", "GAO")
                         ){
  
  # Retrieve the genus names from the plot
  names <- data.frame(do.call('rbind', strsplit(levels(droplevels(heatmap$data$Display)),'; ',fixed=TRUE)))
  names <- data.frame(Genus = names[,genus_pos])
  names$Genus <- as.character(names$Genus)
  
  # Retrieve the function data if not provided
  if (is.null(function_data)) {
    data(MiF, envir = environment())
    function_data <- MiF
  }
  
  # Define some nice colors for plotting
  POS <- "#31a354"
  VAR <- "orange"
  NEG <- "#f03b20"
  NT <- "grey90"
  
  # Make selection if not plotting all functions
  function_data <- function_data[,c("Genus",plotted_functions)]
  
  # Merge the genus and function information
  
  nameFunc <- merge(x = names, y = function_data, all.x = TRUE, all.y = FALSE) 
  
  nameFunc[is.na(nameFunc)] <- "NT"
  
  nameFuncM <- melt(nameFunc, id.vars = "Genus", value.name = "Value", variable.name = "Function")
  
  nameFuncM$Value <- factor(nameFuncM$Value, levels = c("POS", "VAR", "NEG", "NT"))
  nameFuncM$Genus <- factor(nameFuncM$Genus, levels = names$Genus)
  
  
  # Generate the plot
  
  p <- ggplot(nameFuncM, aes(x = Function, y = Genus, color = Value)) +
    geom_point(size = point_size) +
    scale_color_manual(values = c(POS, VAR, NEG, NT), drop = FALSE) +
    theme(axis.text.x = element_text(size = 12, color = "black", angle = 90, hjust = 1, vjust = 0.4),
          axis.text.y = element_blank(),
          axis.title = element_blank(),
          legend.title = element_blank(),
          axis.ticks.length = unit(1, "mm"),
          axis.ticks = element_blank(),
          plot.margin = unit(c(adjust_top,0,adjust_bottom,0), "mm"),
          panel.background = element_blank(),
          panel.grid.major = element_line(color = "grey95"),
          legend.key = element_blank()
    )
  
  return(gridExtra::grid.arrange(heatmap, p, ncol = 2))
}